### ISSUE TITLE
Dependencies added to wrong target

### ISSUE THREAD

**Issue by sfirmery** [please-build/puku#63]
Dependencies seems to be added to the first target of the BUILD file.

Here is a reproducer https://github.com/sfirmery/puku_proto_issue/tree/a5bcc793e48aef422aa80d332cf5e711acfe144b

After running `plz run //tools:puku -- fmt //testproto //test`, dependencies are wrongly added to `//testproto:pb`.

After reverting to the original files, inverting target order in `testproto/BUILD` and rerunning `puku` adds dependencies on `//testproto`.

**Comment by Tatskaari** [comment]
Ah yeah, Puku assumes that you will only have 1 library target in a package. Please is more expressive than Go, and allows you to express things that are not possible with `go build`. Puku tires to map standard go semantics back to BUILD files, so requires that your project be more compliant with `go build`. If you define multiple go_library targets in the same folder, it becomes ambiguous. For example, if you import `github.com/sfirmery/puku_proto_issue/testproto`, how would puku know which `go_library` target in that BUILD file to resolve that import to? 

I think your problem here is actually slightly different, if I understand correctly. You have a version of `proto_library` that doesn't actually provide a go library target for the package, it just outputs some generated source files? The problem is puku is treating `proto_library()` as if it's a `go_library` target, which leads to the problem described above. I think the solution is to make this configurable, so it doesn't automatically treat `proto_library()` as a `go_library` target.

**Comment by sfirmery** [comment]
Thanks for your detailed answer.

Yes it's correct.
The `proto_library` is only used to generate go sources as we cannot add additional go source files to them.

**Comment by Tatskaari** [comment]
I've made excluding the default kinds possible in #69

**Comment by sfirmery** [comment]
Thanks, works perfectly!
